name: CI pipeline

on:
 push:
     branches: [main]
     paths:
       - 'Backend/**' 
       - 'Frontend/**'
       - '.github/workflows/ci.yml'
 pull_request:
     branches: [main]
     paths:
       - 'Backend/**'
       - 'Frontend/**'
 workflow_dispatch:

jobs:
